### ISSUE TITLE
MM3.0 Patch Ordering Fix

### ISSUE THREAD

**Issue by 7ranceaddic7** [Icecovery/Comfortable-Landing#1]
StockPod.cfg
ln41    @PART[Mark1-2Pod]:FOR[ComfortableLanding]:NEEDS[VenStockRevamp]:AFTER[VenStockRevamp]

ln124    @PART[mk1pod]:FOR[ComfortableLanding]:NEEDS[VenStockRevamp]:AFTER[VenStockRevamp]

Remove :NEEDS directives to comply with patch ordering and not produce errors

ln41    @PART[Mark1-2Pod]:FOR[ComfortableLanding]:AFTER[VenStockRevamp]

ln124    @PART[mk1pod]:FOR[ComfortableLanding]:AFTER[VenStockRevamp]

**Comment by Icecovery** [comment]
Fixed in V1.4(20180129)
Thanks for your report and sorry for responding so late.
